export const Products = [
  {
    id: 1,
    title: "Sicilian",
    img: "/temporary/p1.png",
    buyPrice: 20000,
    sellPrice: 25000,
    stock: 60,
  },
  {
    id: 2,
    title: "Bacon Deluxe",
    img: "/temporary/p2.png",
    buyPrice: 15000,
    sellPrice: 20000,
    stock: 100,
  },
  {
    id: 3,
    title: "Bella Napoli",
    img: "/temporary/p3.png",
    buyPrice: 3000,
    sellPrice: 5000,
    stock: 200,
  },
  {
    id: 4,
    title: "Spicy Arrabbiata",
    img: "/temporary/p4.png",
    buyPrice: 48000,
    sellPrice: 60000,
    stock: 30,
  },
  {
    id: 5,
    title: "Jalapeño Fiesta",
    img: "/temporary/p5.png",
    buyPrice: 22000,
    sellPrice: 26000,
    stock: 67,
  },
  {
    id: 6,
    title: "Margherita Magic",
    img: "/temporary/p6.png",
    buyPrice: 8000,
    sellPrice: 12000,
    stock: 55,
  },
  {
    id: 7,
    title: "Garlic Parmesan Linguine",
    img: "/temporary/p7.png",
    buyPrice: 1500,
    sellPrice: 2000,
    stock: 120,
  },
  {
    id: 8,
    title: "Mediterranean Delight",
    img: "/temporary/p8.png",
    buyPrice: 7000,
    sellPrice: 10000,
    stock: 80,
  },
  {
    id: 9,
    title: "Hawaiian Teriyaki",
    img: "/temporary/p9.png",
    buyPrice: 80000,
    sellPrice: 100000,
    stock: 32,
  },
];
